class SourcesMock {
  static final createSourceSuccess = {
    "object": "source",
    "id": "src_test_61ogzjw3to8279z8f6p",
    "livemode": false,
    "location": "/sources/src_test_61ogzjw3to8279z8f6p",
    "amount": 20000,
    "barcode": null,
    "bank": null,
    "created_at": "2024-11-08T08:34:14Z",
    "currency": "THB",
    "email": null,
    "flow": "offline",
    "installment_term": null,
    "ip": "49.237.4.46",
    "absorption_type": null,
    "name": null,
    "mobile_number": null,
    "phone_number": null,
    "platform_type": null,
    "scannable_code": null,
    "billing": null,
    "shipping": null,
    "items": [],
    "references": null,
    "provider_references": null,
    "store_id": null,
    "store_name": null,
    "terminal_id": null,
    "type": "promptpay",
    "zero_interest_installments": null,
    "charge_status": "unknown",
    "receipt_amount": null,
    "discounts": [],
    "promotion_code": null
  };
  static final getSource = {
    "object": "source",
    "id": "src_test_61ogzjw3to8279z8f6p",
    "livemode": false,
    "location": "/sources/src_test_61ogzjw3to8279z8f6p",
    "amount": 20000,
    "barcode": null,
    "bank": null,
    "created_at": "2024-11-08T08:34:14Z",
    "currency": "THB",
    "email": null,
    "flow": "offline",
    "installment_term": null,
    "ip": "49.237.4.46",
    "absorption_type": null,
    "name": null,
    "mobile_number": null,
    "phone_number": null,
    "platform_type": null,
    "scannable_code": null,
    "billing": null,
    "shipping": null,
    "items": [],
    "references": null,
    "provider_references": null,
    "store_id": null,
    "store_name": null,
    "terminal_id": null,
    "type": "promptpay",
    "zero_interest_installments": null,
    "charge_status": "unknown",
    "receipt_amount": null,
    "discounts": [],
    "promotion_code": null
  };
  static final sourceNotFound = {
    "object": "error",
    "location": "https://www.omise.co/api-errors#not-found",
    "code": "not_found",
    "message": "source src_test_61ogzjw3to8279z8f6pk was not found"
  };
  static final invalidPaymentType = {
    "object": "error",
    "location": "https://www.omise.co/api-errors#bad-request",
    "code": "bad_request",
    "message": "type is currently not supported"
  };
}
