name: Dart CI

on: [push, pull_request]

jobs:
  test_and_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for SonarCloud

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.0"

      - name: Install dependencies
        run: |
          dart pub get
          cd example/flutter_example
          flutter pub get

      - name: Run Dart tests with coverage
        # The flutter command is silently executed since we only want the coverage report generated
        # but the dart command does not generate the lcov file.
        run: |
          dart test --coverage=coverage
          flutter test --coverage > /dev/null 2>&1 || true
          ls -l coverage/lcov.info

      - name: Run analysis (Dart)
        run: dart analyze

      - name: Run analysis (Flutter)
        run: |
          cd example/flutter_example
          flutter analyze

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
